### ISSUE TITLE
O começo!

### ISSUE THREAD

**Issue by TiagoDanin** [DesenvolvimentoDeBots/i18n#1]
Esse projeto tem como objetivo traduzir a documentação do Telegram Bot API para Pt-Br. Muitos dos membros do grupo tem dificuldades com a linguagem English.

Para fazer:
- [x] Gerar automaticamente um `api.json` contendo informações da documentação, isso sera feito usando o [JuanPotato/AutoTG](https://github.com/JuanPotato/AutoTG) (Necessário fechamento do issue https://github.com/JuanPotato/AutoTG/issues/1).
- [x] O `api.json` sera o ponto de partida para o gerado um arquivo em Markdown (Em English).
- [x] Fazer integração com uma plataforma de tradução (Preferencialmente o [Crowdin](https://crowdin.com/)).
- [x] Traduções feita na plataforma devem ser salva em um arquivo neste repositório.
- [x] Adicionar o link desse projeto no grupo.
- [X] Script de upload glossary pronto.
- [X] AutoTG funcionar 100% corretamente com a nova documentação.

**Comment by heylouiz** [comment]
Seria legal se o próprio Telegram oferecesse um meio de tradução oficial para essa página, vi que eles tem uma ferramenta oficial para a tradução dos aplicativos:
https://translations.telegram.org/

@TiagoDanin já testou rodar esse AutoTG na página nova? Ainda é possível gerar a api.json ou o software está quebrado?

**Comment by TiagoDanin** [comment]
@heylouiz Eu cheguei a fazer um teste rápido, parece tudo ok. Qualquer coisa faço um fork e aplico as modificações para funcionar corretamente.

**Comment by TiagoDanin** [comment]
Status: Projeto enviando para aprovação da Crowdin.
Novo Status: Projeto aprovado <3 Love Crowdin
